### ISSUE TITLE
Implement API that will retrieve a task by its task ID

### ISSUE THREAD

**Issue by NazWright** [NazWright/task-master#3]
Given that there is a valid task Id attached to the request, 
When an authenticated app or user tries to interface with this API, 
Then they will be given back a list of data that has information on tasks that have been created with this task Id.

### Tasks 

- [ ] Define a route in TaskController.ts for receiving a GET request for task details given the id of the Task.
- [ ] Attach authentication middleware to the controller.
- [ ] Define a function in TaskService to retrieve injected model(s) and prepare a response to send back to the controller. 
- [ ] Define a mapper that takes JSON data and injects our Task model with the data and returns this to our service if needed.
- [ ] Define an entity in a database for tasks & connect this entity to the application
- [ ] Define a Task model
- [ ] Analysis of properties of a task
